### PR TITLE
Update to onnx 1.11.0

### PR DESCRIPTION
**Pull request by jerry73204**
This patch update the 3rd party onnx repo to 1.11.0 and update dependency versions.

### CODE REVIEW

**Comment by oovm** [comment]
@crackcomm 

Can you update the onnx to the latest version? 

I can't load this year's new model.

Thanks!

**Comment by crackcomm** [comment]
@oovm I no longer use this crate. Please consider forking and either publishing a new crate or using a git repository resolution.

**Comment by jerry73204** [comment]
@crackcomm can you archive this repo to inform everyone else to know about the status?

**Comment by crackcomm** [comment]
@jerry73204 good idea.

**Pull request closed without merging**
